### ISSUE TITLE
Problem switching out the my-server.crt.pem

### ISSUE THREAD

**Issue by bluejellybean** [coolaj86/nodejs-ssl-example#1]
Hey there, I've been working at this all day and I'm kind of stuck at this point. I've followed your tutorial and it's worked the best so far in that I can at least get the cert working on your faked ca.

The issue is when I go to switch out the my-server.crt.pem with the one I've received from positiveSLL the browser doesn't say it's untrusted only that the webpage is unavailable. The server itself looks fine as if it was running.

 Any guidance at all would be incredibly helpful as I said, been beating my head against this all day.
Thanks!

**Comment by coolaj86** [comment]
Do you get any error in the console from node? Want to get on skype and show me?

**Comment by bluejellybean** [comment]
No error in console (it looks likes normal). And yeah that would be super helpful. I'll pm you my info when I get home
Thanks!

**Comment by bluejellybean** [comment]
GOT IT! I think a fresh set of eyes and a full night of sleep helped. Thank you so much, your tutorial is fantastic!
The issue was the ordering of my certs.

To anyone who stumbles upon this in the future. You will get at least 3 certs. 1 root, 1+ intermediate, and 1 'server' cert (coolaj86 called it this in the guide). The 'server' cert is called {yourdomainnamehere}.crt on Comodo (this tripped me up hard).

**Comment by coolaj86** [comment]
Please also post that on the YouTube and blog comments and I'll create a troubleshooting section.

—
