### ISSUE TITLE
Let's Encrypt Public Beta: December 3, 2015

### ISSUE THREAD

**Issue by zckrs** [coolaj86/nodejs-ssl-example#7]
This is your reminder :-p

https://letsencrypt.org/2015/11/12/public-beta-timing.html

Thank you for this example.

**Comment by coolaj86** [comment]
Ah, yes, we made https://github.com/Daplie/letsencrypt-express

Take a look at that. It's automatic HTTPS for your node server and it'll work with any of the frameworks (koa, hapi, whatever), not just express.

Also take a look at
- https://daplie.com/articles/lets-encrypt-on-raspberry-pi/
- https://daplie.com/articles/lets-encrypt-on-digital-ocean-with-caddy/
- https://daplie.com/articles/lets-encrypt-in-literally-90-seconds/
- https://caddyserver.com/
