### ISSUE TITLE
Question w/ Live Certs

### ISSUE THREAD

**Issue by calbear47** [coolaj86/nodejs-ssl-example#8]
If I plugged in real certificates I purchased from Network solutions, created a key, and them added them both, could I assume I could test this locally and NOT receive the errors  Secrutiy Waring error from the browser? Logically, my browser should recognize them, and everything should work locally...right? Or am I off base. Great work on this, BTW, this was super easy to understand.

**Comment by coolaj86** [comment]
Yeah, if you update `/etc/hosts` or set the DNS to the intranet machine it'll work.
